Multiple resolutions, multiple models (#135)
* wip, but 3dvar can choose from 2 models and 2 resolutions

* wip

* 3dvar with m6c5, but not using ice analysis yet

* more user options

* FCSTMODEL in wrong place ...

* Only test sst da

* other optional model in the comment

* Issue with mom_override template

* Updated readme

diff --git a/jobs/JJOB_POST b/jobs/JJOB_POST
--- a/jobs/JJOB_POST
+++ b/jobs/JJOB_POST
@@ -1,4 +1,29 @@
 #!/bin/bash
-echo "J_JOB for post"
-echo $CDATE
+set -e
 
+cat <<EOF
+#================================================================================
+#================================================================================
+# JJOB_POST
+#   Cleanup, archive, plot stuff, ...
+#================================================================================
+#================================================================================
+EOF
+
+# Remove BUMP files
+# TODO: After update to soca, bump only needs to be initialized once
+#       per layout.
+if [ -d $RUNCDATE/bump ]; then rm -rf $RUNCDATE/bump/; fi
+
+# Remove model dependent peanuts
+case $FCSTMODEL in
+   "MOM6solo")
+       # TODO: Figure out what needs to be cleaned-up
+       echo "Not implemented yet"
+       ;;
+   "MOM6CICE5")
+       # TODO: Keep something from fcst?
+       if [ -d $RUNCDATE/fcst ]; then rm -rf $RUNCDATE/fcst; fi
+       if [ -d $RUNCDATE/test-emc-m6c5 ]; then rm -rf $RUNCDATE/test-emc-m6c5; fi
+       ;;
+esac
